### GET alla
GET http://localhost:3000/players?sortBy=name&orderBy=desc&search=

### GET test
GET http://localhost:3000/

### Put player
PUT http://localhost:3000/players/1
content-type: application/json; charset=utf-8

{
    "name": "Tomten",
    "jersey": 10000,
    "position": "Goalie",
    "team": "North Pole Orcas"
}

### Post player
POST http://localhost:3000/players
content-type: application/json; charset=utf-8

{
    "name": "Den andra Tomten",
    "jersey": "4",
    "position": "Forward",
    "team": "Hammarby IF"
}